Mylogin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views



from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
    temp,
    home_proj,
    dashboard,

)


from account.views import (
    register_view,
    login_view,
    logout_view,

)

urlpatterns = [	
       
	path('admin/', admin.site.urls),
 
    path('', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('logout/', logout_view, name="logout"),  
    path('register/', register_view, name="register"),
    
    path('home/', home_screen_view, name='home'),    
    path('temp/', temp, name='temp'),    
    path('home-proj/', home_proj, name='home-proj'),
    path('dashboard/', dashboard, name='dashboard'),
    
    
    
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
     
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from account.views import (
	account_view,
)

app_name = 'account'

urlpatterns = [
	path('<user_id>/', account_view, name="view"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os
import uuid


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


def get_profile_image_filepath(self, filename):
	return 'profile_images/' + str(self.pk) + '/profile_image.png'

def get_default_profile_image():
	return "codingwithmitch/logo_1080_1080.png"


class Account(AbstractBaseUser):
	email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 				= models.CharField(max_length=30, unique=True)
	date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin				= models.BooleanField(default=False)
	is_active				= models.BooleanField(default=True)
	is_staff				= models.BooleanField(default=False)
	is_superuser			= models.BooleanField(default=False)
	profile_image			= models.ImageField(max_length=255, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)
	hide_email				= models.BooleanField(default=True)
	Department              = models.ForeignKey("Department", on_delete=models.CASCADE, null=True, blank=True)
	Designation             = models.ForeignKey("Designation", on_delete=models.CASCADE, null=True, blank=True)
	highest_quali			= models.CharField(max_length=200, null=True, blank=True)
	pan_no					= models.CharField(max_length=10, null=True, blank=True)
	GENDER_CHOICES = (       
        ('Male', 'M'),
        ('Female', 'F')
    )
	gender					= models.CharField(verbose_name='Gender(M/F)',max_length=6, choices=GENDER_CHOICES, null=True, blank=True)
	quali_year				= models.CharField(verbose_name='Qualifying Year',max_length=4, null=True, blank=True)
	dt_ob             		= models.DateField(verbose_name='date of birth', null=True, blank=True)
	tot_experience			= models.IntegerField(verbose_name='Total Experience in year', default=0)
 
 
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.username

	def get_profile_image_filename(self):
		return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True

class Department(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created         = models.DateTimeField(auto_now_add=True)
    id              = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return self.name

class Designation(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created         = models.DateTimeField(auto_now_add=True)
    id              = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return self.name    
    

personal/models.py
from django.db import models

# Create your models here.

personal/views.py
from django.shortcuts import render


def home_screen_view(request):
	context = {}
	return render(request, "personal/home2.html", context)

def temp(request):
	context = {}
	return render(request, "personal/temp1.html", context)



def dashboard(request):
	context = {}
	return render(request, "personal/dashboard.html", context)

def home_proj(request):
	context = {}
	return render(request, "personal/home.html", context)

personal/templates/personal/dashboard.html
{% extends 'base.html' %}

{% block content %}

<head>

    <style>
     table{
       background-color:cadetblue 
     } 
     th{
        font-size: 30px;
        font-weight: bold;
        color:darkblue;
     }

     td{
         font-size: 20px;
         font-weight: bold;         
     }

    </style> 

</head> 

<body>

<div style="float:left;margin-left:320px;">
<br>
<br>
<h2 class="text-center">Dashboard</h2>
    <table class="table table-stripped" >
        <thead>
          <tr>
            <th>Particulars</th>
            <th></th>
            <th></th>
            <th>Year-1</th>            
            <th>Year-2</th>
          </tr>
        </thead>

        <tbody>

          <tr>
            <td>No.of Projects</td>
            <td></td>
            <td></td>
            <td class="text-center">10</td>
            <td class="text-center">20</td>          
          </tr>
          <tr>
            <td>No. of Publications</td> 
            <td></td>
            <td></td>
            <td class="text-center">20</td>
            <td class="text-center">30</td>          
          
          </tr>
          <tr>
            <td>No. of Seminers</td>
            <td></td>
            <td></td>
            <td class="text-center">30</td>
            <td class="text-center">40</td>          
            
          </tr>
          <tr>
            <td>No. of Books</td>
            <td></td>
            <td></td>
            <td class="text-center">40</td>
            <td class="text-center">50</td>          
            
          </tr>
          <tr>
            <td>No. of Patents</td>
            <td></td>
            <td></td>
            <td class="text-center">50</td>
            <td class="text-center">60</td>          
            
          </tr>
          <tr>
            <td>No. of Awards</td>
            <td></td>
            <td></td>
            <td class="text-center">60</td>
            <td class="text-center">70</td>          
            
          </tr>

        </tbody>
      </table>
</div> 


</body> 
</html>                                 

{% endblock content %}

personal/templates/personal/home.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
	.my-grid{
		border: 1px solid black;
	}
	.my-grid-item{
		border: 1px solid blue;
	}
</style>

<!-- Flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/ -->
<div class="container-fluid">
    <div class="row">
        <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <!-- sidebar content goes in here -->
            <div class="position-sticky pt-md-5">
              <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                      <span class="ml-2">Dashboard</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:view' user_id=request.user.id %}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                      <span class="ml-2">My Profile</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                      <span class="ml-2">Projects</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                      <span class="ml-2">Publications</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                      <span class="ml-2">Seminars</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                      <span class="ml-2">Books</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                      <span class="ml-2">Patents</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                      <span class="ml-2">Awards</span>
                    </a>
                  </li>
                </ul>
            </div>
              
        </nav>
       
  </div>
  </div>
    
    <!-- insert scripts here
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
   -->
{% endblock content %}

personal/templates/personal/home1.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
	.my-grid{
		border: 1px solid black;
	}
	.my-grid-item{
		border: 1px solid blue;
	}
</style>

<!-- Flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/ -->
<div class="container">
	<div class="my-grid d-flex flex-row justify-content-between">
	<!-- <div class="my-grid d-flex flex-row justify-content-end"> -->
		<p class="my-grid-item m-auto">Item</p>
		<p class="my-grid-item m-auto">Item</p>
		<p class="my-grid-item m-auto">Item</p>
		<p class="my-grid-item m-auto">Item</p>
		<p class="my-grid-item m-auto">Item</p>
	</div>

	<div class="my-grid d-flex flex-column mt-4">
		<p class="my-grid-item mx-auto my-1 p-1">Item</p>
		<p class="my-grid-item mx-auto my-1 p-1">Item</p>
		<p class="my-grid-item mx-auto my-1 p-1">Item</p>
		<p class="my-grid-item mx-auto my-1 p-1">Item</p>
		<p class="my-grid-item mx-auto my-1 p-1">Item</p>
	</div>
	
</div>
{% endblock content %}

personal/templates/personal/home2.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- 
<a href="{% url 'login' %}">jjklj</a>
 -->

{% endblock content %}

personal/templates/personal/temp.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <style>
            table {
                border-collapse: collapse;
            }
            th {
                background-color:green;
                Color:white;
            }
            th, td {
                width:150px;
                text-align:center;
                border:1px solid black;
                padding:5px
              
            }
            .geeks {
                border-right:hidden;
            }
            .gfg {
                border-collapse:separate;
                border-spacing:0 15px;
            }
            h1 {
                color:green;
            }
        </style>
    </head>
    <body>
       
        <h1>GeeksforGeeks</h1>
        <h2>Row spacing in a table</h2>
        <table>
            <tr>
                <th>Employee ID</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Age</th>
            </tr>
        </table>
        <table class = "gfg">
            <tr>
                <td class = "geeks">10001</td>
                <td>Thomas</td>
                <td>M</td>
                <td>32</td>
            </tr>
            <tr>
                <td class = "geeks">10002</td>
                <td>Sally</td>
                <td>F</td>
                <td>28</td>
            </tr>
            <tr>
                <td class = "geeks">10003</td>
                <td>Anthony</td>
                <td>M</td>
                <td>24</td>
            </tr>
        </table>
       
    </body>
</html>

{% endblock content %}

personal/templates/personal/temp1.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
	}
	.field-heading{
		color: var(--secondary-text-color);
	}
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
	.friends-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.person-add-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.friend-text{
		font-weight: 500;
		color: black;
	}
	.friends-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
	.message-btn-text{
		font-weight: 500;
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="codingwithmitch logo" id="id_profile_image" src="{{profile_image}}">
		  		</div>
		  		<p class="mt-4 mb-1 field-heading">Email</p>
		  		{%  if is_self %}
		  			<h5>{{email}}</h5>
		  		{% else %}
		  			{% if hide_email %}
			  			<h5>**********</h5>
			  		{% else %}
			  			<h5>{{email}}</h5>
			  		{% endif %}
			  	{% endif %}
		  		<p class="mt-4 mb-1 field-heading">Username</p>
		  		<h5>{{username}}</h5>

		  		<!-- If Auth user is viewing their own profile -->
		  		{% if is_self %}
		  		<a  class="mt-4 btn btn-primary" href="#">Update</a>
				<div class="d-flex flex-column mt-4">
					<a class="m-auto" href="{% url 'password_change' %}">Change password</a>
				</div>
		  		{% endif %}
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			<!-- THEM to YOU -->
			{% if request_sent == 0 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="friend-text align-items-center mr-2">Accept Friend Request</span>
					<span id="id_cancel_{{id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>cancel</span>
  					<span id="id_confirm_{{id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>check</span>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
				{% if is_friend == False and is_self == False %}
						<!-- You sent them a request -->
						{% if request_sent == 1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}
						<!-- No requests have been sent -->
						{% if request_sent == -1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-primary" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
				{% endif %}
					
					
				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
						</button>
						<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
							<a class="dropdown-item" href="#" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
						</div>
					</div>
				{% endif %}
				
				<!-- TODO -->
				<!-- Friend list link -->
		  		<div class="d-flex flex-column pt-4">
					<a href="#">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 friends-icon">contact_page</span><span class="friend-text">Friends (0)</span>
						</div>
					</a>
				</div>

			</div>

			<!-- TODO -->
			{#% if friend_requests %#}
			<div class="card m-2 px-4 pb-4">
				<!-- Friend requests -->
		  		<div class="d-flex flex-column pt-4">
					<a href="#">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 person-add-icon">person_add</span><span class="friend-text">Friend Requests (0)</span>
						</div>
					</a>
				</div>
			</div>
			{#% endif %#}

			{% if is_friend %}
				<div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4" onclick="createOrReturnPrivateChat('{{id}}')">
					<span class="material-icons m-auto">
					message
					</span>
					<span class="message-btn-text m-auto pl-2">Message</span>
				</div>
			{% endif %}

		</div>
		{% endif %}

		
	</div>
</div>


<script type="text/javascript">

	// called from base_js.html
	//preloadImage("{{profile_image|safe}}", 'id_profile_image')

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}


	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			//sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			//cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			//removeFriend("{{id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		//acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		//declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
	
</script>

{#% include 'snippets/send_friend_request.html' %#}
{#% include 'snippets/accept_friend_request.html' %#}
{#% include 'snippets/decline_friend_request.html' %#}
{#% include 'snippets/cancel_friend_request.html' %#}
{#% include 'snippets/remove_friend.html' %#}
{#% include 'chat/create_or_return_private_chat.html' %#}



{% endblock content %}